import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Link from "next/link";
import Themebtn from "@/components/Themebtn";
import { Home, Menu, Book, Heart, Settings, Bookmark } from "lucide-react";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";

import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetTrigger } from "@/components/ui/sheet";
import Player from "@/components/Player";
import SearchDialog from "@/components/SearchDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="body" className={inter.className + "relative"}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <SearchDialog />
          <div className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
            <div className="hidden border-r bg-muted/40 md:block">
              <div className="flex h-full max-h-screen flex-col gap-2">
                <div className="flex gap-4 items-center border-b py-10 lg:h-[60px] lg:px-6">
                  {/* <Link href="/" className="flex items-center gap-2 font-semibold">
              <BookOpenText className="h-6 w-6" />
              <span className="">Al-Siraj App</span>
            </Link> */}
                  <Avatar>
                    <AvatarImage
                      src="https://github.com/shadcn.png"
                      alt="@shadcn"
                    />
                    <AvatarFallback>CN</AvatarFallback>
                  </Avatar>
                  <div className="name">
                    <p className="text-sm">As-salamu alaykum</p>
                    <p>Waleed Nasir</p>
                  </div>
                </div>
                <div className="flex-1">
                  <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
                    <Link
                      href="/"
                      className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Home className="h-4 w-4" />
                      Dashboard
                    </Link>
                    <Link
                      href="/surah"
                      className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Book className="h-4 w-4" />
                      Surah
                      {/* <Badge className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full">
                  6
                </Badge> */}
                    </Link>
                    <Link
                      href="favorites"
                      // className="flex items-center gap-3 rounded-lg bg-muted px-3 py-2 text-primary transition-all hover:text-primary"
                      className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Heart className="h-4 w-4" />
                      Favorites
                    </Link>
                    <Link
                      href="/bookmark"
                      className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Bookmark className="h-4 w-4" />
                      Bookmark
                    </Link>
                    <Link
                      href="/playlist"
                      className="flex items-center gap-3 rounded-lg px-3 py-2 text-muted-foreground transition-all hover:text-primary"
                    >
                      <Settings className="h-4 w-4" />
                      Settings
                    </Link>
                    <Themebtn />
                  </nav>
                </div>
                <div className="mt-auto p-4">
                  <nav className="grid items-start px-2 text-sm font-medium lg:px-4">
                    {/* <Themebtn /> */}
                    {/* <Link
                      href="/playlist"
                      className="flex items-center gap-3 rounded-lg text-muted-foreground transition-all hover:text-primary"
                    >
                      <Settings className="h-4 w-4" />
                      Settings
                    </Link> */}
                  </nav>
                </div>
              </div>
            </div>
            <div className="flex flex-col p-2">
              <Sheet>
                <SheetTrigger asChild>
                  <Button
                    variant="outline"
                    size="icon"
                    className="shrink-0 md:hidden mb-3"
                  >
                    <Menu className="h-5 w-5 " />
                    <span className="sr-only">Toggle navigation menu</span>
                  </Button>
                </SheetTrigger>
                <SheetContent side="left" className="flex flex-col">
                  <nav className="grid gap-2 text-lg font-medium">
                    <div className="profile-info flex flex-row gap-5">
                      <Avatar>
                        <AvatarImage
                          src="https://github.com/shadcn.png"
                          alt="@shadcn"
                        />
                        <AvatarFallback>CN</AvatarFallback>
                      </Avatar>
                      <div className="name">
                        <p className="text-base">As-salamu alaykum</p>
                        <p className="text-lg">Waleed Nasir</p>
                      </div>
                    </div>
                    {/* mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground */}
                    <Link
                      href="/"
                      className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
                    >
                      <Home className="h-4 w-4" />
                      Dashboard
                    </Link>
                    <Link
                      href="/surah"
                      className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
                    >
                      <Book className="h-4 w-4" />
                      Surah
                      {/* <Badge className="ml-auto flex h-6 w-6 shrink-0 items-center justify-center rounded-full">
                  6
                </Badge> */}
                    </Link>
                    <Link
                      href="favorites"
                      // className="flex items-center gap-3 rounded-lg bg-muted px-3 py-2 text-primary transition-all hover:text-primary"
                      className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
                    >
                      <Heart className="h-4 w-4" />
                      Favorites
                    </Link>
                    <Link
                      href="/bookmark"
                      className="mx-[-0.65rem] flex items-center gap-4 rounded-xl px-3 py-2 text-muted-foreground hover:text-foreground"
                    >
                      <Bookmark className="h-4 w-4" />
                      Bookmark
                    </Link>
                  </nav>
                  <div className="mt-auto p-4">
                    <nav className="grid gap-2 text-lg font-medium">
                      <Themebtn />
                      <Link
                        href="/playlist"
                        className="mx-[-0.65rem] flex items-center gap-4 rounded-xl text-muted-foreground hover:text-foreground"
                      >
                        <Settings className="h-4 w-4" />
                        Settings
                      </Link>
                    </nav>
                  </div>
                </SheetContent>
              </Sheet>
              {children}
            </div>
          </div>
          <Player />
        </ThemeProvider>
      </body>
    </html>
  );
}
